apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::149996181182:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-VP29XIIHUSMT
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::149996181182:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-17T07:59:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1729"
  uid: 86bc0f86-5ba1-402c-b84a-a5d3d45850f4
 
